# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-02 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterevent', '0003_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservReport',
            fields=[
                ('observId', models.IntegerField(db_column='observId', primary_key=True, serialize=False)),
                ('date', models.DateField(max_length=10)),
                ('observName', models.CharField(max_length=20)),
                ('overflow', models.BooleanField(max_length=20)),
            ],
            options={
                'db_table': 'ObservReport',
                'managed': False,
            },
        ),
    ]
